[package]
name = "neutron-star-rt"
version = "0.1.0"
authors = ["earlz <earlz@earlz.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
